language: node_js
node_js:
  - '0.11'
  - '0.10'
notifications:
  slack:
    rooms:
      - secure: AmkUF4r56PdRj6OyhwwoutRTO/cXx0oUOvElmme6OWDtrugEzRAfauzwWoCpOBevAXUJcJ4eFjX0uaxAP3f6QSzCeFvhk2h7Qava7egu+tI+oeLG028TCc3L8HLTCEELLjP90N/XsLUv9dCUvJaKECEn83Go8FPBSuOGnEw6yC8=
